name: Deploy to Firebase

on:
  push:
    branches:
      - main
     
jobs:
  main:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - uses: actions/checkout@v4
    - uses: jsryudev/deploy-firebase-functions@v20.0.0
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_ID }}