name: Deploy to Firebase

on:
  push:
    branches:
      - main
                
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v2

      - name: Download deps
        working-directory: functions
        run: npm install

      - name: Deploy
        run: |-
          npx firebase use ${{ secrets.FIREBASE_PROJECT_ID }} 
          npx firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
